chain = "mainnet"
reth_datadir = "/data/fast/rbuilder/reth"

backtest_fetch_eth_rpc_url = "http://127.0.0.1:8504"
backtest_fetch_eth_rpc_parallel = 800
backtest_fetch_output_file = "~/.rbuilder/backtest/main.sqlite"
backtest_fetch_mempool_data_dir = "~/.rbuilder/mempool-data"
backtest_results_store_path = "~/.rbuilder/backtest/results.sqlite"

sbundle_mergeable_signers = []

backtest_builders = ["mp-ordering", "mgp-ordering"]

[[builders]]
name = "mgp-ordering"
algo = "ordering-builder"
discard_txs = true
sorting = "mev-gas-price"
failed_order_retries = 1
drop_failed_orders = true

[[builders]]
name = "mp-ordering"
algo = "ordering-builder"
discard_txs = true
sorting = "max-profit"
failed_order_retries = 1
drop_failed_orders = true


[[builders]]
name = "fair-inclusion"
algo = "ordering-builder"
discard_txs = true
sorting = "mev-gas-price"
failed_order_retries = 0
drop_failed_orders = true
build_duration_deadline_ms = 3000